<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>karata-cards</AssemblyName>
    <ContainerRepository>peter-mghendi/karata-cards</ContainerRepository>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Karata.Runtime\Karata.Runtime.csproj" />
    <ProjectReference Include="..\Karata.ServiceDefaults\Karata.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
