<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Keycloak" Version="13.4.6-preview.1.26319.6" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageVersion Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageVersion Include="CodeBeam.MudBlazor.Extensions" Version="8.3.0" />
    <PackageVersion Include="Consolonia" Version="11.3.12.6" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Duende.IdentityModel.OidcClient" Version="7.1.0" />
    <PackageVersion Include="Keycloak.AuthServices.Authentication" Version="3.0.0" />
    <PackageVersion Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />

    <!-- To patch CVE-2026-49451: Remove when upgrading. -->
    <PackageVersion Include="Microsoft.OpenApi" Version="2.9.0" /> 
    <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageVersion Include="MudBlazor" Version="9.5.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageVersion Include="Photino.Blazor" Version="4.0.13" />
    <PackageVersion Include="QRCoder" Version="1.8.0" />
    <PackageVersion Include="RestSharp" Version="114.0.0" />
    <PackageVersion Include="Splat.Microsoft.Extensions.DependencyInjection" Version="17.1.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageVersion Include="System.Reactive" Version="6.1.0" />
    <PackageVersion Include="TextCopy" Version="6.2.1" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.17" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>