<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>karata-platform</AssemblyName>
        <ContainerRepository>peter-mghendi/karata-platform</ContainerRepository>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="CmdScale.EntityFrameworkCore.TimescaleDB" />
        <PackageReference Include="CmdScale.EntityFrameworkCore.TimescaleDB.Design" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Karata.Runtime\Karata.Runtime.csproj" />
        <ProjectReference Include="..\Karata.ServiceDefaults\Karata.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
