### Introspect Bot
GET {{Karata.Bot.Host}}/api/bots/{{Karata.Bot.Slug}}
Accept: application/json

### Invite Bot
POST {{Karata.Bot.Host}}/api/bots/{{Karata.Bot.Slug}}/games
Accept: application/json
Content-Type: application/json

{ 
  "room": "019e697b-2e2e-7c75-b553-d277089ebcd3",
  "password": null
}