### Introspect Bot
GET {{Karata.Bot.Host}}/api/bots/{{Karata.Bot.Slug}}
Accept: application/json

### Invite Bot
POST {{Karata.Bot.Host}}/api/bots/{{Karata.Bot.Slug}}/games
Accept: application/json
Content-Type: application/json

{ 
  "room": "019cd439-c7db-7649-adbc-d3f9174faeb0",
  "password": null
}