<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Platforms>AnyCPU</Platforms>
<!--    <ApplicationIcon>favicon.ico</ApplicationIcon>-->
  </PropertyGroup>

  <ItemGroup>
    <Content Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="favicon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Photino.Blazor" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Karata.Surface\Karata.Surface.csproj" />
  </ItemGroup>

</Project>
