// <auto-generated />
using System;
using Karata.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Karata.Platform.Data.Migrations
{
    [DbContext(typeof(KarataPlatformContext))]
    [Migration("20260706031653_AddActivity")]
    partial class AddActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Karata.Platform.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "OccurredAt");

                    b.ToTable("Activity");

                    b
                        .HasAnnotation("TimescaleDB:ChunkSkipColumns", "OccurredAt")
                        .HasAnnotation("TimescaleDB:ChunkTimeInterval", "86400000")
                        .HasAnnotation("TimescaleDB:IsHypertable", true)
                        .HasAnnotation("TimescaleDB:MigrateData", true)
                        .HasAnnotation("TimescaleDB:TimeColumnName", "OccurredAt");
                });

            modelBuilder.Entity("Karata.Platform.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Karata.Platform.Models.Activity", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ActivityId");

                            b1.Property<DateTimeOffset>("ActivityOccurredAt");

                            b1.HasKey("ActivityId", "ActivityOccurredAt");

                            b1.ToTable("Activity");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId", "ActivityOccurredAt");
                        });

                    b.OwnsOne("System.Collections.Generic.List<Karata.Kit.Platform.Models.ActionData>", "Actions", b1 =>
                        {
                            b1.Property<Guid>("ActivityId");

                            b1.Property<DateTimeOffset>("ActivityOccurredAt");

                            b1.Property<int>("Capacity");

                            b1.HasKey("ActivityId", "ActivityOccurredAt");

                            b1.ToTable("Activity");

                            b1
                                .ToJson("Actions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId", "ActivityOccurredAt");
                        });

                    b.Navigation("Actions")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
