name: Draft GitHub Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set version
        id: params
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT  

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.params.outputs.version }}
          generate_release_notes: true