name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5            

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install Android workload
        run: dotnet workload install android

      - name: Install Webassembly workload
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore Karata.slnf

      - name: Build
        run: dotnet build --configuration Release --no-restore Karata.slnf

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal Karata.slnf
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Publish
        run: dotnet publish --configuration Release -p PublishProfile=DefaultContainer -p ContainerRegistry=ghcr.io src/Karata.Server/Karata.Server.csproj