<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\Karata.Bot\Karata.Bot.csproj" />
    <ProjectReference Include="..\Karata.Cards\Karata.Cards.csproj" />
    <ProjectReference Include="..\Karata.Desktop\Karata.Desktop.csproj" />
    <ProjectReference Include="..\Karata.Platform\Karata.Platform.csproj" />
    <ProjectReference Include="..\Karata.Web\Karata.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>2899b1a4-5385-45c4-bbc3-337ea265b692</UserSecretsId>
  </PropertyGroup>

</Project>
